# Generated by Django 3.2.6 on 2021-09-02 09:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_DimensionPlanta', models.CharField(max_length=50, verbose_name='DimensionPlanta')),
            ],
            options={
                'verbose_name': 'DimensionPlanta',
                'verbose_name_plural': 'DimensionPlantas',
            },
        ),
        migrations.CreateModel(
            name='LugarPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_Planta', models.CharField(max_length=50, verbose_name='LugarPlanta')),
            ],
            options={
                'verbose_name': 'LugarPlanta',
                'verbose_name_plural': 'LugarPlantas',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Planta', models.CharField(max_length=50, unique=True)),
                ('dimension_Planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.dimensionplanta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_TipoPlanta', models.CharField(max_length=50, verbose_name='TipoPlanta')),
            ],
            options={
                'verbose_name': 'TipoPlanta',
                'verbose_name_plural': 'TipoPlantas',
            },
        ),
        migrations.CreateModel(
            name='PublicacionesPlantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia_Pub', models.ImageField(upload_to='planta')),
                ('fecha_Sembrada', models.DateField()),
                ('sombra', models.BooleanField()),
                ('sol', models.BooleanField()),
                ('cuidados', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lugar_Sembrada_Pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.lugarplanta')),
                ('planta_Pub', models.ManyToManyField(to='index.Planta')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='tipo_Planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.tipoplanta'),
        ),
    ]
